// GENERATED by scripts/build-dungeon-map-legends.js -- do not edit.
// Sources: data/map/dungeon-maps/Classic-ClassicEra.lua and
// data/dungeons/Classic-Classic.lua (Atlas addon data, local-only, not committed).
// Re-run that script by hand if either source dump changes.

export type DungeonMapMarker = { marker: string; label: string; color: string };

export const DUNGEON_MAP_LEGENDS: Partial<Record<string, DungeonMapMarker[]>> = {
  "ragefire-chasm": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Oggleflint",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Taragaman the Hungerer",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Jergosh the Invoker",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Bazzalan",
      "color": "#e8e8e8"
    }
  ],
  "shadowfang-keep": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B-C",
      "label": "Walkway",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Deathstalker Adamant",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Razorclaw the Butcher (Random, Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Baron Silverlaine",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Commander Springvale",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Odo the Blindwatcher (Random, Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Fenrus the Devourer",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Wolf Master Nandos (Random, Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Archmage Arugal",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Fel Steed",
      "color": "#e8e8e8"
    }
  ],
  "the-stockade": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Targorr the Dread (Varies)",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Kam Deepfury",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Hamhock",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Bazil Thredd",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Dextren Ward",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Bruegal Ironknuckle (Rare)",
      "color": "#e8e8e8"
    }
  ],
  "scholomance": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B-C",
      "label": "Stairs",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Blood Steward of Kirtonos",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Kirtonos the Herald (Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Jandice Barov",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "The Deed to Tarren Mill",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Rattlegore (Lower)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Marduk Blackpool",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Ras Frostwhisper",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Instructor Malicia",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Doctor Theolen Krastinov",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Torch Lever",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Secret Chest",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Alchemy Lab",
      "color": "#8fd467"
    }
  ],
  "deadmines": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Exit",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Rhahk'Zor",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Miner Johnson (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Sneed",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Gilnid",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Defias Gunpowder",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Captain Greenskin",
      "color": "#e8e8e8"
    }
  ],
  "uldaman": [
    {
      "marker": "A",
      "label": "Entrance (Front)",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Entrance (Back)",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Baelog",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Remains of a Paladin",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Revelosh",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Ironaya",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Obsidian Sentinel",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Annora <Master Enchanter>",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Ancient Stone Keeper",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Galgann Firehammer",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Grimlok",
      "color": "#e8e8e8"
    }
  ],
  "maraudon": [
    {
      "marker": "A",
      "label": "Entrance (Orange)",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Entrance (Purple)",
      "color": "#8a99ff"
    },
    {
      "marker": "C",
      "label": "Entrance (Portal)",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Veng <The Fifth Khan> (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Noxxion",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Razorlash",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Maraudos <The Fourth Khan> (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Lord Vyletongue",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Meshlok the Harvester (Rare, Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Celebras the Cursed",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Landslide",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Tinkerer Gizlock",
      "color": "#e8e8e8"
    }
  ],
  "sunken-temple": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Stairs",
      "color": "#8a99ff"
    },
    {
      "marker": "C",
      "label": "Troll Minibosses (Upper)",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Altar of Hakkar",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Dreamscythe",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Avatar of Hakkar",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Jammal'an the Prophet",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Morphaz (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Shade of Eranikus",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Spawn of Hakkar (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Elder Starsong (Lunar Festival)",
      "color": "#e8e8e8"
    }
  ],
  "sm-graveyard": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Interrogator Vishas",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Ironspine (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Azshir the Sleepless (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Fallen Champion (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Bloodmage Thalnos",
      "color": "#e8e8e8"
    }
  ],
  "sm-library": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Houndmaster Loksey",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Arcanist Doan",
      "color": "#e8e8e8"
    }
  ],
  "sm-armory": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Herod",
      "color": "#e8e8e8"
    }
  ],
  "sm-cathedral": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "High Inquisitor Fairbanks",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Scarlet Commander Mograine",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "High Inquisitor Whitemane",
      "color": "#e8e8e8"
    }
  ],
  "wailing-caverns": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Lady Anacondra",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Lord Pythas",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Lord Cobrahn",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Skum",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Lord Serpentis (Upper)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Verdan the Everliving (Upper)",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Mutanus the Devourer",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Kresh (Varies)",
      "color": "#e0ad5c"
    },
    {
      "marker": "2",
      "label": "Deviate Faerie Dragon (Rare, Varies)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Ebru <Disciple of Naralex>",
      "color": "#8fd467"
    }
  ],
  "gnomeregan": [
    {
      "marker": "A",
      "label": "Entrance (Front)",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Entrance (Back)",
      "color": "#8a99ff"
    },
    {
      "marker": "C-F",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Grubbis",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Viscous Fallout (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Electrocutioner 6000",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Crowd Pummeler 9-60",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Mekgineer Thermaplugg",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Murd Doc <S.A.F.E.>",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "The Clean Zone",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "B.E Barechus <S.A.F.E.>",
      "color": "#8fd467"
    },
    {
      "marker": "4",
      "label": "Face <S.A.F.E.>",
      "color": "#8fd467"
    },
    {
      "marker": "5",
      "label": "Hann Ibal <S.A.F.E.>",
      "color": "#8fd467"
    }
  ],
  "blackrock-depths": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B-D",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "E",
      "label": "The Molten Core",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "High Interrogator Gerstahn",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Lord Roccor (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Houndmaster Grebmar",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Bael'Gar",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Lord Incendius",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Fineous Darkvire (Wanders)",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "The Vault",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Pyromancer Loregrain",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Ring of Law",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Panzor the Invincible (Rare, Wanders)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Jalinda Sprig <Morgan's Militia>",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Kevin Dawson <Morgan's Militia>",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Prospector Seymour <Morgan's Militia>",
      "color": "#8fd467"
    },
    {
      "marker": "4",
      "label": "Abandoned Mole Machine",
      "color": "#8fd467"
    },
    {
      "marker": "5",
      "label": "The Shadowforge Lock",
      "color": "#8fd467"
    },
    {
      "marker": "6",
      "label": "Blacksmithing Plans",
      "color": "#8fd467"
    },
    {
      "marker": "7",
      "label": "Mayara Brightwing <Morgan's Militia>",
      "color": "#8fd467"
    },
    {
      "marker": "8",
      "label": "Lokhtos Darkbargainer <The Thorium Brotherhood>",
      "color": "#8fd467"
    },
    {
      "marker": "9",
      "label": "Abandoned Mole Machine",
      "color": "#8fd467"
    }
  ],
  "dire-maul-east": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "C",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "D",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "E",
      "label": "Exit",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Lethtendris",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Hydrospawn",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Zevrim Thornhoof (Upper)",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Alzzin the Wildshaper",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Pusillin (Chase Begins)",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Pusillin (Chase Ends)",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Old Ironbark/Ironbark the Redeemed",
      "color": "#8fd467"
    }
  ],
  "dire-maul-west": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B-E",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Tendris Warpwood",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Magister Kalendris",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Illyanna Ravenoak",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Immol'thar",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Prince Tortheldrin",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Tsu'zee (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Estulan <The Highborne>",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Pylons",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Ancient Equine Spirit",
      "color": "#8fd467"
    },
    {
      "marker": "4",
      "label": "Shen'dralar Ancient",
      "color": "#8fd467"
    },
    {
      "marker": "5",
      "label": "The Athenaeum",
      "color": "#8fd467"
    }
  ],
  "dire-maul-north": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Guard Mol'dar",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Stomper Kreeg",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Guard Fengus",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Guard Slip'kik",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Captain Kromcrush",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "King Gordok",
      "color": "#e8e8e8"
    }
  ],
  "lbrs": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Blackrock Mountain",
      "color": "#8a99ff"
    },
    {
      "marker": "C",
      "label": "Upper Blackrock Spire",
      "color": "#8a99ff"
    },
    {
      "marker": "D-G",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Highlord Omokk",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Shadow Hunter Vosh'gajin",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "War Master Voone",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Mother Smolderweb",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Urok Doomhowl (Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Quartermaster Zigris",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Halycon",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Overlord Wyrmthalak",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Burning Felguard (Rare, Summon)",
      "color": "#e0ad5c"
    },
    {
      "marker": "2",
      "label": "Spirestone Butcher (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "3",
      "label": "Spirestone Battle Lord (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "4",
      "label": "Bannok Grimaxe (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "5",
      "label": "Crystal Fang (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "6",
      "label": "Ghok Bashguud (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Acride <Scarshield Legion>",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Elder Stonefort (Lunar Festival)",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Roughshod Pike",
      "color": "#8fd467"
    }
  ],
  "zulfarrak": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Gahz'rilla (Summon)",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Sandfury Executioner",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Nekrum Gutchewer and Shadow Priest Sezz'ziz",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Chief Ukorz Sandscalp",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Witch Doctor Zum'rah",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Antu'sul",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Sandarr Dunereaver (Rare)",
      "color": "#e0ad5c"
    },
    {
      "marker": "2",
      "label": "Hydromancer Velratha",
      "color": "#e0ad5c"
    },
    {
      "marker": "3",
      "label": "Theka the Martyr",
      "color": "#e0ad5c"
    },
    {
      "marker": "4",
      "label": "Dustwraith (Rare, Varies)",
      "color": "#e0ad5c"
    },
    {
      "marker": "5",
      "label": "Zerillis (Rare, Wanders)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Elder Wildmane (Lunar Festival)",
      "color": "#8fd467"
    }
  ],
  "blackfathom-deeps": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Ghamoo-ra",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Lorgalis Manuscript",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Lady Sarevess",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Argent Guard Thaelrid",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Gelihast",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Lorgus Jett (Varies)",
      "color": "#e8e8e8"
    }
  ],
  "razorfen-kraul": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Roogug",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Aggem Thorncurse",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Death Speaker Jargba",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Overlord Ramtusk",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Agathelos the Raging",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Blind Hunter (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Charlga Razorflank",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "Willix the Importer",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "Earthcaller Halmgar (Rare)",
      "color": "#e8e8e8"
    }
  ],
  "razorfen-downs": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Tuten'kash",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Henry Stern",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Mordresh Fire Eye",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Glutton",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Ragglesnout (Rare, Varies)",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Amnennar the Coldbringer",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Plaguemaw the Rotting",
      "color": "#e8e8e8"
    }
  ],
  "ubrs": [
    {
      "marker": "A",
      "label": "Entrance",
      "color": "#8a99ff"
    },
    {
      "marker": "B",
      "label": "Blackrock Spire (Lower)",
      "color": "#8a99ff"
    },
    {
      "marker": "C-E",
      "label": "Connection",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Pyroguard Emberseer",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Solakar Flamewreath",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Darkstone Tablet",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Jed Runewatcher (Rare)",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Goraluk Anvilcrack",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Warchief Rend Blackhand",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Awbee",
      "color": "#e8e8e8"
    },
    {
      "marker": "8",
      "label": "The Beast",
      "color": "#e8e8e8"
    },
    {
      "marker": "9",
      "label": "General Drakkisath",
      "color": "#e8e8e8"
    }
  ],
  "stratholme-live": [
    {
      "marker": "A",
      "label": "Entrance (Front)",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Hearthsinger Forresten",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "The Unforgiven",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Timmy the Cruel",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Commander Malor",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Willey Hopebreaker",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Instructor Galford",
      "color": "#e8e8e8"
    },
    {
      "marker": "7",
      "label": "Balnazzar",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Stratholme Courier",
      "color": "#e0ad5c"
    },
    {
      "marker": "3",
      "label": "Risen Hammersmith (Summon)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "King's Square Postbox",
      "color": "#8fd467"
    },
    {
      "marker": "2",
      "label": "Festival Lane Postbox",
      "color": "#8fd467"
    },
    {
      "marker": "3",
      "label": "Elder Farwhisper (Lunar Festival)",
      "color": "#8fd467"
    },
    {
      "marker": "4",
      "label": "Market Row Postbox",
      "color": "#8fd467"
    }
  ],
  "stratholme-undead": [
    {
      "marker": "A",
      "label": "Entrance (Front)",
      "color": "#8a99ff"
    },
    {
      "marker": "1",
      "label": "Baroness Anastari",
      "color": "#e8e8e8"
    },
    {
      "marker": "2",
      "label": "Nerub'enkan",
      "color": "#e8e8e8"
    },
    {
      "marker": "3",
      "label": "Maleki the Pallid",
      "color": "#e8e8e8"
    },
    {
      "marker": "4",
      "label": "Magistrate Barthilas (Varies)",
      "color": "#e8e8e8"
    },
    {
      "marker": "5",
      "label": "Ramstein the Gorger",
      "color": "#e8e8e8"
    },
    {
      "marker": "6",
      "label": "Lord Aurius Rivendare",
      "color": "#e8e8e8"
    },
    {
      "marker": "1",
      "label": "Black Guard Swordsmith (Summon)",
      "color": "#e0ad5c"
    },
    {
      "marker": "1",
      "label": "Archmage Angela Dosantos <Brotherhood of the Light>",
      "color": "#8fd467"
    }
  ]
};
