import lootData from "@/data/dungeon-loot.json";
import { dungeons, getDungeon, type Dungeon } from "@/lib/dungeons";

// Community-crowdsourced dungeon loot tables, from wowtbc.gg -- NOT
// beta-client-confirmed the way talent/spellbook data is (see
// components/reference/LootDisclaimer.tsx, rendered on every loot page).
// Generated by scripts/build-dungeon-loot.js from the latest
// data/sources/wowtbc-loot-*.json snapshot, mirroring how
// data/spellbooks.json is generated from the talentsforever pulls.
export type LootItem = {
  name: string;
  slot: string | null;
  type: string | null;
  dropChance: number | null;
  // The source showed "<N%" rather than an exact value (e.g. "<1%") --
  // render dropChance with a leading "<" rather than as an exact number.
  dropChanceUnder: boolean;
  isNew: boolean;
  // wowtbc.gg itself shows "Not Yet Discovered" for this item's slot/type --
  // genuinely unknown at the source, not a gap in our own scraping.
  unknown: boolean;
};

export type LootBoss = {
  name: string;
  items: LootItem[];
};

export type QuestReward = {
  faction: "Alliance" | "Horde" | null;
  questName: string;
  level: number | null;
  items: LootItem[];
};

export type DungeonLoot = {
  wowtbcSlug: string;
  wowtbcName: string;
  bosses: LootBoss[];
  questRewards: QuestReward[];
};

type LootDataFile = {
  source: string;
  pulledDate: string;
  dungeons: Record<string, DungeonLoot>;
};

const data = lootData as LootDataFile;

// dungeons.json splits Stratholme into "stratholme-undead" and
// "stratholme-live" (matching Classic's two-side convention, used by the
// Level Ranges chart) -- wowtbc.gg doesn't split its loot table by side at
// all, so both ids resolve to the one combined "stratholme" loot entry.
const LOOT_KEY_OVERRIDES: Record<string, string> = {
  "stratholme-undead": "stratholme",
  "stratholme-live": "stratholme",
};

function lootKeyFor(dungeonId: string): string {
  return LOOT_KEY_OVERRIDES[dungeonId] ?? dungeonId;
}

export function getDungeonLoot(dungeonId: string): DungeonLoot | undefined {
  return data.dungeons[lootKeyFor(dungeonId)];
}

export function hasDungeonLoot(dungeonId: string): boolean {
  return lootKeyFor(dungeonId) in data.dungeons;
}

export type DungeonLootSummary = Dungeon & {
  bossCount: number;
  questRewardCount: number;
};

// Every dungeon that has loot data, sorted by level ascending (levelMin then
// levelMax) -- same ordering the existing Level Ranges chart's own row-
// packing is built from, so the loot index table reads consistently with
// it rather than introducing its own sort.
export function getDungeonLootIndex(): DungeonLootSummary[] {
  return dungeons
    .filter((d) => hasDungeonLoot(d.id))
    .map((d) => {
      const loot = getDungeonLoot(d.id)!;
      return { ...d, bossCount: loot.bosses.length, questRewardCount: loot.questRewards.length };
    })
    .sort((a, b) => a.levelMin - b.levelMin || a.levelMax - b.levelMax);
}

export function getDungeonWithLoot(dungeonId: string): { dungeon: Dungeon; loot: DungeonLoot } | undefined {
  const dungeon = getDungeon(dungeonId);
  const loot = getDungeonLoot(dungeonId);
  if (!dungeon || !loot) return undefined;
  return { dungeon, loot };
}
