// GENERATED by scripts/build-map-data-imports.js (runs as `prebuild`) -- do not edit.
import easternKingdomsMeta from "@/data/map/eastern-kingdoms/meta.json";
import easternKingdomsZones from "@/data/map/eastern-kingdoms/zones.json";
import easternKingdomsAreas from "@/data/map/eastern-kingdoms/zone-areas.json";
import kalimdorMeta from "@/data/map/kalimdor/meta.json";
import kalimdorZones from "@/data/map/kalimdor/zones.json";
import kalimdorAreas from "@/data/map/kalimdor/zone-areas.json";

export const MAP_DATA: Record<string, { meta: object; zones: object; areas: object }> = {
  "eastern-kingdoms": { meta: easternKingdomsMeta, zones: easternKingdomsZones, areas: easternKingdomsAreas },
  "kalimdor": { meta: kalimdorMeta, zones: kalimdorZones, areas: kalimdorAreas },
};
