// GENERATED by scripts/build-og-backgrounds.js (runs as `prebuild`) -- do not edit.
import fs from "fs/promises";
import path from "path";

export const OG_BACKGROUNDS: Record<string, () => Promise<Buffer>> = {
  "/images/blog/alchemy/hero1.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/alchemy/hero1.jpg")),
  "/images/blog/beta_login_queue.png": () => fs.readFile(path.join(process.cwd(), "public/images/blog/beta_login_queue.png")),
  "/images/blog/blacksmithing/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/blacksmithing/hero.webp")),
  "/images/blog/classic-plus-new/undead-paladin-mount.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/classic-plus-new/undead-paladin-mount.webp")),
  "/images/blog/cooking/hero.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/cooking/hero.jpg")),
  "/images/blog/deep-dive-panel-notes-2/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/deep-dive-panel-notes-2/hero.webp")),
  "/images/blog/enchanting/hero.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/enchanting/hero.jpg")),
  "/images/blog/engineering/hero.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/engineering/hero.jpg")),
  "/images/blog/first-aid/hero.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/first-aid/hero.jpg")),
  "/images/blog/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/hero.webp")),
  "/images/blog/mount-hyjal/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/mount-hyjal/hero.webp")),
  "/images/blog/tailoring/WoW_Forever_Announce_Zones_NewWater_006.jpg": () => fs.readFile(path.join(process.cwd(), "public/images/blog/tailoring/WoW_Forever_Announce_Zones_NewWater_006.jpg")),
  "/images/blog/zephras-isle/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/blog/zephras-isle/hero.webp")),
  "/images/guides/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/guides/hero.webp")),
  "/images/hero/homepage-hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/hero/homepage-hero.webp")),
  "/images/reference/hero.webp": () => fs.readFile(path.join(process.cwd(), "public/images/reference/hero.webp")),
};
