// GENERATED by scripts/build-og-backgrounds.js (runs as `prebuild`) -- do not edit.
// Values are pre-shrunk JPEGs (assets/og-backgrounds/), ready to embed as data URIs.
import fs from "fs/promises";
import path from "path";

export const OG_BACKGROUNDS: Record<string, () => Promise<Buffer>> = {
  "/images/blog/alchemy/hero1.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__alchemy__hero1.jpg")),
  "/images/blog/beta_login_queue.png": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__beta_login_queue.jpg")),
  "/images/blog/blacksmithing/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__blacksmithing__hero.jpg")),
  "/images/blog/classic-plus-new/undead-paladin-mount.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__classic-plus-new__undead-paladin-mount.jpg")),
  "/images/blog/cooking/hero.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__cooking__hero.jpg")),
  "/images/blog/deep-dive-panel-notes-2/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__deep-dive-panel-notes-2__hero.jpg")),
  "/images/blog/enchanting/hero.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__enchanting__hero.jpg")),
  "/images/blog/engineering/hero.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__engineering__hero.jpg")),
  "/images/blog/first-aid/hero.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__first-aid__hero.jpg")),
  "/images/blog/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__hero.jpg")),
  "/images/blog/mount-hyjal/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__mount-hyjal__hero.jpg")),
  "/images/blog/tailoring/WoW_Forever_Announce_Zones_NewWater_006.jpg": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__tailoring__WoW_Forever_Announce_Zones_NewWater_006.jpg")),
  "/images/blog/zephras-isle/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__blog__zephras-isle__hero.jpg")),
  "/images/guides/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__guides__hero.jpg")),
  "/images/hero/homepage-hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__hero__homepage-hero.jpg")),
  "/images/reference/hero.webp": () => fs.readFile(path.join(process.cwd(), "assets/og-backgrounds/images__reference__hero.jpg")),
};
