import questIndex from "@/data/quests/index.json";
import dungeonMembership from "@/data/quests/dungeon-membership.json";
import type { LootItem } from "@/lib/dungeon-loot";

// Listing and query layer for quests. Everything here reads the build-time
// index generated by scripts/build-quests.js (data/quests/index.json), which
// merges foreverchanges.pro's full scrape with the cMaNGOS and Wowhead sources
// and records per-field provenance (data/quests/provenance.json). Nothing here
// touches the raw source files at request time.
//
// Per-quest detail (narrative, chain, map points) lives in one shard per quest
// and is read by lib/quest-detail.ts, which only the statically generated
// /quests/[questId] page imports -- keeping the shard directory out of the
// listing's serverless bundle.

export type QuestReputation = { faction: string; factionId: number | null; amount: number };

export type QuestSide = "Alliance" | "Horde" | "Both";
export type QuestLocationKind = "zone" | "dungeon" | "raid" | "battleground" | "sort" | "unknown";
// Which upstream the narrative text came from. "foreverchanges" is the
// detail-page scrape itself (its text is attributed to cMaNGOS and Wowhead on
// that site); "cmangos" and "wowhead" are the direct sources.
export type QuestTextSource = "foreverchanges" | "cmangos" | "wowhead";

// A reward row. The item fields are the catalog's LootItem; qty is the count
// the quest grants (1 for most, more for stackable reagents and tokens).
export type QuestRewardItem = LootItem & { qty: number };

// The listing row -- what /reference/quests filters, sorts and renders. The
// detail shard is a superset of this (see QuestDetail below).
export type Quest = {
  id: number;
  name: string;
  // Quest level ("Level" column) -- the level the quest itself is tuned for.
  // May differ from requiredLevel for a breadcrumb quest offered below its own level.
  level: number | null;
  // Minimum character level to pick the quest up.
  requiredLevel: number | null;
  side: QuestSide;
  typeTag: string | null;
  locationKind: QuestLocationKind;
  // Resolved zone name when locationKind is "zone" and the area id is one the
  // site tracks; null otherwise.
  locationName: string | null;
  // Which /reference/map/[continent] page locationName lives on, for linking the
  // location text to the map. Null whenever locationName is.
  locationContinent: string | null;
  // The raw areaId behind locationName, needed for the #sel=zone:<areaId> deep link.
  locationZoneId: number | null;
  xp: number;
  money: number;
  choiceRewards: QuestRewardItem[];
  guaranteedRewards: QuestRewardItem[];
  // Null when the quest has no narrative text from any source.
  textSource: QuestTextSource | null;
};

export type QuestNarrative = {
  details: string | null;
  objectives: string | null;
  offerRewardText: string | null;
  requestItemsText: string | null;
  endText: string | null;
  objectiveText: string[];
};

export type QuestChainLink = { id: number; name: string };

// One named NPC or object on a quest, with its zone and map coordinates when
// the source gave them (zone-relative percent, 0-100).
export type QuestNpcPoint = { name: string; zone: string | null; x: number | null; y: number | null };

// xPct/yPct are zone-relative percent coordinates, used against the zone map
// image's own pixel dimensions (see QuestMap.tsx).
export type QuestMapMarker = { kind: "start" | "end"; npcName: string; xPct: number; yPct: number };

// One mini-map's worth of render-ready data -- a quest gets one per distinct
// mappable zone its start/turn-in points fall in.
export type QuestMapGroup = {
  zoneId: number;
  zoneName: string;
  // Which /reference/map/[continent] page this zone lives on, for the "open on
  // the full map" link. Null only if the zone id has no continent in the map data.
  continent: string | null;
  imageUrl: string;
  markers: QuestMapMarker[];
};

// One colored difficulty band: the level at which a quest's color starts.
// WoW's own order is red -> orange -> yellow -> green -> grey (grey is the
// scrape's spelling; there is no "gray" in the source data).
export type QuestDifficultyBand = { color: "red" | "orange" | "yellow" | "green" | "grey"; level: number };

export type QuestChainQuest = {
  questId: number;
  name: string;
  isCurrent: boolean;
  level: string | null;
  objectiveText: string | null;
  giverName: string | null;
  giverZone: string | null;
  xpText: string | null;
  // icon is the catalog stem (e.g. "inv_belt_08"), not a path.
  rewardItem: { itemId: number | null; href: string | null; icon: string | null; name: string | null; quality: string | null; qty: number } | null;
  // A row that stands for several quests at once, e.g. "One quest for each
  // class" -- each variant is its own quest id and gets its own link.
  variants: { questId: number; label: string }[] | null;
};

export type QuestChainStep = { stepNumber: number; isCurrentStep: boolean; quests: QuestChainQuest[] };

// The quest's own chain as foreverchanges lists it, with parallel quests in a
// step kept together. Null when the quest has no chain.
export type QuestChain = { subtitle: string | null; steps: QuestChainStep[] };

export type QuestItemRef = { itemId: number | null; name: string | null; icon: string | null; quality: string | number | null; qty: number; sources?: string[] };

export type QuestDetail = Quest & {
  // Classic's XP, shown on hover when Forever changed the quest's XP.
  classicXp: number | null;
  classRestriction: string | null;
  difficultyBands: QuestDifficultyBand[];
  repeatable: boolean;
  timelimit: string | null;
  profession: string | null;
  shareable: string | null;
  // foreverchanges' own status tag for the quest's text and rewards.
  status: "new" | "changed" | "unchanged" | null;
  statusNote: string | null;
  footerSourceNote: string | null;
  narrative: QuestNarrative | null;
  narrativeSource: QuestTextSource | null;
  prevQuest: QuestChainLink | null;
  nextQuest: QuestChainLink | null;
  nextQuestInChain: QuestChainLink | null;
  giverName: string | null;
  turnInName: string | null;
  // Item-started quests: the scrape's own text for the start ("an item: X").
  startItemText: string | null;
  startNpcs: QuestNpcPoint[];
  endNpcs: QuestNpcPoint[];
  reputation: QuestReputation[];
  mentionedItems: LootItem[];
  mapGroups: QuestMapGroup[];
  chain: QuestChain | null;
  objectiveItems: QuestItemRef[];
  providedItems: QuestItemRef[];
  inScrape: boolean;
};

export const LOCATION_KIND_TABS: { value: QuestLocationKind | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "zone", label: "Zone" },
  { value: "dungeon", label: "Dungeon" },
  { value: "raid", label: "Raid" },
  { value: "battleground", label: "Battleground" },
  { value: "sort", label: "Other" },
];

let cache: Quest[] | null = null;

function loadAll(): Quest[] {
  if (!cache) cache = (questIndex as { quests: Quest[] }).quests;
  return cache;
}

export function getQuestLocationKindCounts(): Record<QuestLocationKind | "all", number> {
  const all = loadAll();
  const counts: Record<QuestLocationKind | "all", number> = {
    all: all.length,
    zone: 0,
    dungeon: 0,
    raid: 0,
    battleground: 0,
    sort: 0,
    unknown: 0,
  };
  for (const quest of all) counts[quest.locationKind]++;
  return counts;
}

// A dungeon that lists at least one catalog quest on its loot page, for the
// dungeon dropdown on /reference/quests. `count` is how many catalog quests it
// lists (a quest can belong to more than one dungeon, e.g. Stratholme).
export type QuestDungeonOption = { id: string; name: string; count: number };

export function getQuestDungeonOptions(): QuestDungeonOption[] {
  return dungeonMembership.dungeons
    .map((d) => ({ id: d.id, name: d.name, count: d.questIds.length }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

let dungeonQuestSets: Map<string, Set<number>> | null = null;

function dungeonQuestIds(dungeonId: string): Set<number> | undefined {
  if (!dungeonQuestSets) {
    dungeonQuestSets = new Map(dungeonMembership.dungeons.map((d) => [d.id, new Set(d.questIds)]));
  }
  return dungeonQuestSets.get(dungeonId);
}

export function getQuestCount(): number {
  return loadAll().length;
}

// Every quest id in the index -- the sitemap's list and the detail page's
// static params.
export function getAllQuestIds(): number[] {
  return loadAll().map((quest) => quest.id);
}

export function getTextSourceCounts(): Record<QuestTextSource, number> {
  const counts: Record<QuestTextSource, number> = { foreverchanges: 0, cmangos: 0, wowhead: 0 };
  for (const quest of loadAll()) {
    if (quest.textSource) counts[quest.textSource]++;
  }
  return counts;
}

// Columns worth sorting. Rewards and the narrative columns have no single
// orderable value, so they're deliberately left out.
export type QuestSortKey = "name" | "level" | "requiredLevel" | "side" | "location" | "xp";

export type QuestQuery = {
  locationKind?: QuestLocationKind | "all";
  // A dungeon id from getQuestDungeonOptions(). Narrows whatever else is
  // selected rather than replacing it.
  dungeon?: string;
  q?: string;
  side?: QuestSide | "all";
  levelMin?: number;
  levelMax?: number;
  sort?: QuestSortKey;
  dir?: "asc" | "desc";
  page?: number;
  pageSize?: number;
};

// A sort key's comparable value for one quest. Missing numbers sort after
// everything regardless of direction, matching a spreadsheet's blank cells.
function sortValue(quest: Quest, key: QuestSortKey): string | number | null {
  switch (key) {
    case "name":
      return quest.name.toLowerCase();
    case "level":
      return quest.level;
    case "requiredLevel":
      return quest.requiredLevel;
    case "side":
      return quest.side;
    case "location":
      return (quest.locationName ?? quest.locationKind).toLowerCase();
    case "xp":
      return quest.xp;
  }
}

function compareQuests(a: Quest, b: Quest, key: QuestSortKey, dir: "asc" | "desc"): number {
  const va = sortValue(a, key);
  const vb = sortValue(b, key);
  if (va === null && vb === null) return 0;
  if (va === null) return 1;
  if (vb === null) return -1;
  const cmp = va < vb ? -1 : va > vb ? 1 : 0;
  return dir === "asc" ? cmp : -cmp;
}

export type QuestQueryResult = {
  quests: Quest[];
  total: number;
  page: number;
  pageSize: number;
  pageCount: number;
};

export function formatMoney(copper: number): string {
  if (copper <= 0) return "--";
  const gold = Math.floor(copper / 10000);
  const silver = Math.floor((copper % 10000) / 100);
  const remainder = copper % 100;
  const parts: string[] = [];
  if (gold > 0) parts.push(`${gold}g`);
  if (silver > 0) parts.push(`${silver}s`);
  if (remainder > 0 || parts.length === 0) parts.push(`${remainder}c`);
  return parts.join(" ");
}

export function queryQuests({
  locationKind = "all",
  dungeon,
  q = "",
  side = "all",
  levelMin,
  levelMax,
  sort,
  dir = "asc",
  page = 1,
  pageSize = 40,
}: QuestQuery): QuestQueryResult {
  let quests = loadAll();
  if (locationKind !== "all") quests = quests.filter((quest) => quest.locationKind === locationKind);
  if (dungeon) {
    const members = dungeonQuestIds(dungeon);
    quests = members ? quests.filter((quest) => members.has(quest.id)) : [];
  }
  if (side !== "all") quests = quests.filter((quest) => quest.side === side || quest.side === "Both");
  if (levelMin !== undefined) quests = quests.filter((quest) => quest.level !== null && quest.level >= levelMin);
  if (levelMax !== undefined) quests = quests.filter((quest) => quest.level !== null && quest.level <= levelMax);

  const needle = q.trim().toLowerCase();
  if (needle) quests = quests.filter((quest) => quest.name.toLowerCase().includes(needle));

  if (sort) quests = [...quests].sort((a, b) => compareQuests(a, b, sort, dir));

  const total = quests.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), pageCount);
  const start = (safePage - 1) * pageSize;

  return { quests: quests.slice(start, start + pageSize), total, page: safePage, pageSize, pageCount };
}
