import spellbooksData from "@/data/spellbooks.json";

// One rank's full tooltip -- generated by scripts/build-spellbooks.js from
// talentsforever.com's per-rank spell_desc entries (Class|Spell|Rank N).
// `rank`/`variant` are both null/undefined for a single-rank spell with no
// numbered-rank suffix in the source key; `variant` carries a non-numeric
// suffix when the source data keys a spell by something other than rank
// (e.g. a shapeshift-form name) rather than losing that distinction.
export type SpellRank = {
  rank: number | null;
  variant?: string;
  level: number | null;
  description: string;
  lines: [string, string][];
  school?: string;
  coefficient?: string;
  confirmed: boolean;
  source?: string;
  classicStatus?: "changed" | "same" | "new" | "note";
  classicDescription?: string;
  classicLines?: [string, string][];
  // The vendor's own explanation for a `classicStatus: "note"` rank -- a
  // free-text caveat (e.g. Presence of Mind: "Still an Arcane talent in
  // Forever. It comes with the talent point.") rather than a diffable
  // before/after pair like classicDescription.
  classicNote?: string;
  // Present when this rank's Classic-era name differed from Forever's --
  // e.g. "Curse of Agony" for what Forever calls Bane of Agony. Drives the
  // RENAMED tag; a spell can be `classicStatus: "changed"` without this
  // (a REWORKED-tagged spell -- same name, different numbers/text).
  renamedFrom?: string;
  // A vendor footnote on this specific rank's own data, distinct from any
  // Classic comparison -- e.g. Instant Poison IV: the beta client's own
  // tooltip literally shows "1,800 charges" (its 30 min duration in
  // seconds, mis-slotted into the charges field); `description` already
  // carries the corrected 130, this is the explanation for the mismatch.
  note?: string;
};

export type SpellbookEntry = {
  name: string;
  icon?: string;
  passive?: boolean;
  // Derived from the vendor's own per-class `talents` list (spells a talent
  // grants, not trained normally) -- not something we name-match ourselves.
  talent?: boolean;
  tag?: string;
  // Set on entries using the inv_misc_questionmark fallback because a real
  // icon hasn't been verified yet -- easy to grep for and swap in later.
  iconPlaceholder?: boolean;
  // Absent for General-tab entries (Attack, Shoot, ...) -- that tab is
  // still demo-sourced (see ClassSpellbook.tabs below) and those baseline
  // commands have no real spell tooltip in the game's own files either.
  ranks?: SpellRank[];
};

export type SpellbookTab = {
  name: string;
  // Present on a tab that isn't derived from a talent tree (so getTreeIcon
  // has no talent-tree data to fall back to) -- currently just Rogue's
  // "Poisons" recipe tab. Falls back to getTreeIcon's own heuristic/
  // overrides when absent, same as before this field existed.
  icon?: string;
  // A short caption shown under the tab's header, e.g. Poisons' "recipes:
  // each one makes the poison you put on a weapon" -- absent on every
  // other tab today.
  note?: string;
  spells: SpellbookEntry[];
};

// Per-class in-game verification, straight from the vendor's own
// `checked` field -- present only for classes whose trainer has actually
// been read in-game (as of a given pull, this may be a subset of all 9;
// check data/spellbooks.json directly rather than assuming coverage).
export type SpellbookVerification = {
  npc: string;
  zone: string;
  date: string;
  gameBuild: string;
  rows: number;
  lacked: number;
  levelDiffs: number;
};

export type ClassSpellbook = {
  demoRace: string;
  notes: string[];
  notOpened: string[];
  tabs: SpellbookTab[];
  checked?: SpellbookVerification;
  // Spells the trainer no longer sells at all (distinct from a rename) --
  // e.g. Paladin's Sanctity Aura, Shaman's Fire Nova Totem as of the
  // 2026-09-19 pull. Not currently surfaced in the UI; kept so the data
  // isn't silently dropped.
  gone?: string[];
};

export type SpellbooksData = {
  source: string;
  classes: Record<string, ClassSpellbook>;
};

export const spellbooks: SpellbooksData = spellbooksData as SpellbooksData;

export const SPELLBOOK_CLASS_ORDER = [
  "warrior",
  "paladin",
  "hunter",
  "rogue",
  "priest",
  "shaman",
  "mage",
  "warlock",
  "druid",
];
