import talentSpellLinksData from "@/data/talent-spell-links.json";

// Which other spells/talents a talent's description names by name -- e.g.
// Bloodthrill mentions Rend and Overpower, Healing Light mentions Holy
// Light/Flash of Light/Holy Shock. Generated by
// scripts/build-talent-spell-links.js (see that script for how matches are
// found and data/sources/README.md for the vendor snapshot it reads rank
// text from) -- regenerate it, don't hand-edit data/talent-spell-links.json.
export type LinkedSpell = {
  name: string;
  kind: "spell" | "talent";
  // "Warrior spell, rank 4" for a trainer spell, "Talent · Holy, row 5" for
  // a talent-granted ability -- matches talentsforever.com's own two label
  // formats for these two source types.
  source: string;
  description: string;
  icon?: string;
};

const TALENT_SPELL_LINKS = talentSpellLinksData as Record<string, LinkedSpell[]>;

export function getLinkedSpells(talentId: string): LinkedSpell[] {
  return TALENT_SPELL_LINKS[talentId] ?? [];
}

export type DescriptionSegment = { text: string; linked: boolean };

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Splits a rank's description text on the talent's own linked-spell names
// (longest name first, so "Flash of Light" isn't cut short by a shorter
// name that happens to be a substring) so the caller can render matches as
// inline highlights -- matches talentsforever.com's white/underlined
// in-description spell names. Re-splits per rendered rank rather than
// reusing the max-rank match positions computed at data-build time, since
// the exact wording (and which names appear) can differ rank to rank.
export function splitTextWithLinks(text: string, links: LinkedSpell[]): DescriptionSegment[] {
  if (links.length === 0) return [{ text, linked: false }];
  const names = [...links.map((l) => l.name)].sort((a, b) => b.length - a.length);
  const pattern = new RegExp(`\\b(${names.map(escapeRegExp).join("|")})\\b`, "g");

  const segments: DescriptionSegment[] = [];
  let lastIndex = 0;
  for (const match of text.matchAll(pattern)) {
    const index = match.index ?? 0;
    if (index > lastIndex) segments.push({ text: text.slice(lastIndex, index), linked: false });
    segments.push({ text: match[0], linked: true });
    lastIndex = index + match[0].length;
  }
  if (lastIndex < text.length) segments.push({ text: text.slice(lastIndex), linked: false });
  return segments;
}
