// GENERATED by scripts/build-zone-map-images.js -- do not edit.
// areaIds with a /images/zone-maps/<areaId>.jpg in public/ for the quest-detail mini-map.
export const ZONE_MAP_IMAGE_IDS = new Set<number>([1,3,4,8,10,11,12,14,15,16,17,28,33,36,38,40,41,44,45,46,47,51,85,130,139,141,148,215,267,331,357,361,400,405,406,440,490,493,616,618,1377,1497,1519,1537,1637,1638,1657,2597,3277,3358,16591,16593,16606,16651]);
