import LootItemPill from "@/components/reference/LootItemPill";
import type { ResolvedLevelingRank } from "@/lib/profession-utils";

// Matches foreverchanges.pro/professions/<id>#leveling's own layout
// (rank-tier header with its requirement text, then one row per skill
// range: item, source caption, craft count, materials) -- studied live
// before building, not copied markup. The "~N crafts" count string in the
// source data has no space before "crafts" (a scrape artifact, same class
// of bug as the item-tooltip fixes in Part A) -- reformatted at render time
// rather than in the data itself, since this file wasn't generated by this
// site's own pipeline.
export default function ProfessionLevelingGuide({ leveling, professionId }: { leveling: ResolvedLevelingRank[]; professionId: string }) {
  return (
    <div className="mt-4 flex flex-col gap-4">
      {/* Active Work in Progress Disclaimer Card */}
      <div className="flex items-start gap-3 rounded-lg border border-blue-500/30 bg-blue-500/10 p-4 text-blue-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="mt-0.5 h-5 w-5 shrink-0 text-blue-400"
        >
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="16" x2="12" y2="12" />
          <line x1="12" y1="8" x2="12.01" y2="8" />
        </svg>
        <div className="flex flex-col gap-1 text-sm">
          <span className="font-semibold text-blue-100">Work in Progress</span>
          <p className="text-blue-300/90">
            This leveling guide is currently an active work in progress. Crafting steps and material requirements are subject to adjustments.
          </p>
        </div>
      </div>

      {leveling.map((rank, ri) => {
        const isArtisan = rank.rank.toLowerCase() === "artisan" || ri === leveling.length - 1;

        return (
          <div key={rank.rank} className="rounded-lg border border-border bg-surface">
            <div className="border-b border-border bg-surface-hover/40 px-4 py-2">
              <span className="font-heading text-sm font-semibold uppercase tracking-wide text-accent">{rank.rank}</span>
              <span className="ml-2 text-xs text-foreground-muted">{rank.requirement}</span>
            </div>

            {isArtisan && (
              <div className="border-b border-border bg-red-500/10 px-4 py-2.5 text-xs ">
                <span className="font-semibold text-amber-300">Note:</span> We can only get to 225 skill in the beta, therefore the leveling guide data for this rank is speculative.
              </div>
            )}

            <div className="flex flex-col gap-2.5 p-3">
              {rank.steps.map((step, si) => (
                <div key={si} className="flex flex-col gap-1.5">
                  {/* Primary Step Row */}
                  <div
                    className="-mx-3 flex flex-wrap items-center gap-x-3 gap-y-1 rounded-sm px-3 py-1 text-sm even:bg-surface-hover/30"
                  >
                    <span className="w-16 shrink-0 text-xs font-medium text-foreground-muted">
                      {step.range[1] != null ? (
                        <>
                          {step.range[0]}&ndash;{step.range[1]}
                        </>
                      ) : (
                        step.range[0]
                      )}
                    </span>
                    <LootItemPill item={step.item} tooltipId={`prof:${professionId}:lvl:${ri}:${si}`} context="catalog" />
                    <span className="text-xs text-foreground-muted">{step.source}</span>
                      {/* Additional step properties/craft counts can be rendered here */}
                      {/* Distinct from the muted source/mats text so the craft
                          estimate is easy to pick out at a glance -- same
                          "give the number its own color" hierarchy this page's
                          rank header (text-accent) already uses, not the orange/
                          yellow/green/grey skill-threshold colors, which mean a
                          specific different thing (ProfessionSkillColors). */}
                    <span className="text-xs font-medium text-accent">
                      {step.count.replace(/^(~?\d+)crafts?$/, "$1 crafts")}
                    </span>
                    {/* iconOnly: icon+name for 3-4 reagents was wide enough to
                        push this row onto a second line -- the Recipes tab's
                        reagent list is untouched and still shows the name.
                        Hover/focus still gets the full tooltip either way. */}
                    <div className="flex flex-wrap gap-1">
                      {step.mats.map((mat, mi) => (
                        <LootItemPill
                          key={mi}
                          item={mat.item}
                          tooltipId={`prof:${professionId}:lvl:${ri}:${si}:mat:${mi}`}
                          context="catalog"
                          qty={mat.qty}
                          iconOnly
                        />
                      ))}
                    </div>
                  </div>

                  {step.notes && (
                    <div className="-mx-3 ml-6 flex items-start gap-2 rounded-sm border-l-2 border-amber-400/50 bg-amber-400/5 px-3 py-1.5 text-xs">
                      <span className="shrink-0 font-semibold text-amber-300">Note</span>
                      <p className="text-foreground-muted">{step.notes}</p>
                    </div>
                  )}

                  {/* Alternative Steps (if available) */}
                  {step.alternatives && step.alternatives.map((alt, ai) => (
                    <div
                      key={ai}
                      className="-mx-3 ml-6 flex flex-wrap items-center gap-x-3 gap-y-1 rounded-sm border-l-2 border-accent/40 bg-surface-hover/10 px-3 py-1 text-sm"
                    >
                      <span className="w-16 shrink-0 text-xs font-semibold text-accent">
                        Alt
                      </span>
                      
                      <LootItemPill 
                        item={alt.item} 
                        tooltipId={`prof:${professionId}:lvl:${ri}:${si}:alt:${ai}`} 
                        context="catalog" 
                      />
  
                      {alt.source && (
                        <span className="text-xs text-foreground-muted">{alt.source}</span>
                      )}
                      
                      {alt.count && (
                        <span className="text-xs font-medium text-accent">
                          {alt.count.replace(/^(~?\d+)crafts?$/, "$1 crafts")}
                        </span>
                      )}
                    
                      {alt.mats && alt.mats.length > 0 && (
                        <div className="flex flex-wrap  gap-1">
                          {alt.mats.map((mat, mi) => (
                            <LootItemPill
                              key={mi}
                              item={mat.item}
                              tooltipId={`prof:${professionId}:lvl:${ri}:${si}:alt:${ai}:mat:${mi}`}
                              context="catalog"
                              qty={mat.qty}
                              iconOnly
                            />
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        );
      })}
    </div>
  );
}
